# This is the example pressure file for the MIRA Datalogger file

# the filename used to search for the pressure file looks like:
# filename = basename + "%Y-%m-%d" + "*.dat"
filename_parameters:
  basename: ""
  time_format: "%Y-%m-%d"
  ending: "_Averaged_vaisala.csv"

dataframe_parameters:
  pressure_key: "Pressure"
  datetime_key: "SystemUTC"
  datetime_fmt: "ISO8601"
  